### ISSUE TITLE
Seq2Seq 코드 문제

### ISSUE THREAD

**Issue by 1nsunym** [golbin/TensorFlow-Tutorials#24]
[Seq2Seq](https://github.com/golbin/TensorFlow-Tutorials/blob/master/10%20-%20RNN/03%20-%20Seq2Seq.py) 파일 구동 시  다음과 같은 에러가 발생합니다.

```
Traceback (most recent call last):
  File "test.py", line 68, in <module>
    input_batch, output_batch, target_batch = make_batch(seq_data)
  File "test.py", line 25, in make_batch
    output_batch.append(np.eye(dic_len)[output])
IndexError: index 62 is out of bounds for axis 0 with size 48

```

Tensorflow version 1.4.0을 사용하고 있습니다.

**Comment by jin-y** [comment]
test.py 라는 파일은 없는데요. 원본 스크립트도 실행시 문제가 있는지, 혹시 뭔가를 수정하신건 아닌지 확인 부탁드립니다.

**Comment by golbin** [comment]
test.py 라는 파일은 없는데요. 원본 스크립트도 실행시 문제가 있는지, 혹시 뭔가를 수정하신건 아닌지 확인 부탁드립니다.

**Comment by 1nsunym** [comment]
위 파일에서는 comment만 지우고 돌렸구요, 혹시나 해서 새로 받아서 돌렸습니다.

```
Traceback (most recent call last):
  File "03 - Seq2Seq.py", line 101, in <module>
    input_batch, output_batch, target_batch = make_batch(seq_data)
  File "03 - Seq2Seq.py", line 37, in make_batch
    output_batch.append(np.eye(dic_len)[output])
IndexError: index 62 is out of bounds for axis 0 with size 48
```
원본파일과의 다른점은 첫줄에 아래와 같은 utf-8 인코딩 관련 라인을 삽입했습니다.
```
 # -*- coding: utf-8 -*-
```

**Comment by golbin** [comment]
파이썬 버전 3.5 이상, 텐서플로 버전 1.2 이상이 맞나요?

**Comment by 1nsunym** [comment]
더 낮은 버젼의 파이썬을 쓰고 있었습니다 ㅜㅜ 죄송합니다. 책 잘 보고 있습니다.
