### ISSUE TITLE
5장 Saver 예제 File load 관련 error[VS 환경 해결]

### ISSUE THREAD

**Issue by youchangCho** [golbin/TensorFlow-Tutorials#52]
안녕하세요. 
Saver 예제에서 data.csv 파일을 로드하지 못합니다. 

# 환경
visual studio 2017 에서 Anaconda 를 버추얼로 실행 합니다. 
프로젝트는 Visual studio 2017 에서 Python 프로젝트로 생성 하였습니다. 

# error Message
```
... import tensorflow as tf
... 
>>> import numpy as np
>>> data = np.loadtxt('./data.csv', delimiter=',',
...                   unpack=True, dtype='float32')
... 
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "C:\ProgramData\Anaconda3\lib\site-packages\numpy\lib\npyio.py", line 962, in loadtxt
    fh = np.lib._datasource.open(fname, 'rt', encoding=encoding)
  File "C:\ProgramData\Anaconda3\lib\site-packages\numpy\lib\_datasource.py", line 266, in open
    return ds.open(path, mode, encoding=encoding, newline=newline)
  File "C:\ProgramData\Anaconda3\lib\site-packages\numpy\lib\_datasource.py", line 624, in open
    raise IOError("%s not found." % path)
OSError: ./data.csv not found.

```
./data.csv 파일은 소스 파일과 동일한 위치에 있습니다. 
따로 만든 파일이 문제가 될 수 있어 git 에서 받은 파일로 대치 해봤지만 동일한 문제가 발생 합니다. 

# 예상
혹시 Visual studio 에서 버추얼로 실행 하여 이런 문제가 발생 할 수 있는 걸까요?

**Comment by youchangCho** [comment]
# 해결
상대 경로의 문제 입니다. 
 Visual studio 에 연결 해서 작업을 하는데 './' 의 경로가 해당 위치를 가리키지 않는거 같습니다. 
경로를 절대 경로로 코딩하여 불러오니 잘 되는 것을 확인 하였습니다. 

경로 접근시 \\ 를 반드시 해주셔야 합니다. 

이 해결 책은 Visual Studio 에서 Anaconda  를 버추얼로 설정 한뒤 작업 하는 환경 입니다.

**Comment by youchangCho** [comment]
이슈를 닫으면 다른 분들이 보기 힘들어 다시 열었습니다.
